
a : lab_0a.s
	as -o lab_0a.o lab_0a.s
	ld -o lab_0a lab_0a.o

b: lab_0b.s
	as -o lab_0b.o lab_0b.s
	ld -o lab_0b lab_0b.o

c: lab_0c.s
	as -o lab_0c.o lab_0c.s
	ld -o lab_0c lab_0c.o 

.PHONY : clean	

clean:
	rm *.o		